### ISSUE TITLE
Windows OS alternative

### ISSUE THREAD

**Issue by ofuochi** [shekhargulati/day20-stanford-sentiment-analysis-demo#4]
I'm fairly new to sentiment analysis. Please is there an alternative for windows users?

**Comment by shekhargulati** [comment]
@ofuochi this is just a Java application you should be able to run it on Windows as well.

**Comment by ofuochi** [comment]
Ok. Let me try it out. Thank you

**Comment by ofuochi** [comment]
Hi. I've tried it on windows but I  get error from this line of code in the SentimentAnalyzer class
`Tree tree = sentence.get(SentimentCoreAnnotations.AnnotatedTree.class);`
My eclipse compiler says "SentimentCoreAnnotations.AnnotatedTree cannot be resolved into a class"
I think am getting the error because am using the latest `stanford-corenlp-3.6.0-models.jar` library
How do I resolve this? Should I use an earlier version of the stanford core npl?
